### ISSUE TITLE
Please help me.

### ISSUE THREAD

**Issue by jeonniga** [emersonmde/anchor-chain#1]
How can I use for llama3?  it's only supported for openai. is it right?
if you support llama, it seemd to perfect.

**Comment by emersonmde** [comment]
I just added support for running open source models though [Ollama](https://ollama.com/) in `v0.4.2`. See [this example](https://github.com/emersonmde/anchor-chain/blob/main/examples/ollama.rs) for using a local Ollama instance with `llama3` installed. Hope this helps!

I plan to add support for directly running LLMs using the rustformers [`llm`](https://github.com/rustformers/llm) crate in the future.
